server:
  port: 9999
  servlet:
    context-path: /

spring:
  # 数据库配置
  datasource:
    # 基本配置
    url: jdbc:mysql://localhost:3306/im?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: wztxz19971029
    # druid配置 (参考阿里云推荐配置)
    druid:
      # 配置初始化大小、最小、最大
      initial-size: 5
      min-idle: 10
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # prepared statement
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      # 配置test的时间点
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      # 配置监控统计拦截的filters
      filters: stat
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 2000