package com.xiaoci.im.mapper;

import com.xiaoci.im.entity.po.ChatMessage;
import com.xiaoci.im.entity.po.ChatMessageExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface ChatMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    long countByExample(ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    int deleteByExample(ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    int insert(ChatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    int insertSelective(ChatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    List<ChatMessage> selectByExampleWithRowbounds(ChatMessageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    List<ChatMessage> selectByExample(ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    ChatMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatMessage record, @Param("example") ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatMessage record, @Param("example") ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatMessage record);
}